launch_config:
  renderer: RayTracedLighting
  headless: true
resolution: [512, 512]
num_frames: 5
clear_previous_semantics: false
writer: KittiWriter
writer_config:
  output_dir: _out_kitti
  colorize_instance_segmentation: true